export const interestList = [
  {id: 1, courseName: 'C languages'},
  {id: 2, courseName: 'React'},
  {id: 3, courseName: 'Angular JS'},
  {id: 4, courseName: 'Python'},
  {id: 5, courseName: 'Ruby'},
  {id: 6, courseName: 'Go language'},
  {id: 7, courseName: 'Swift'},
  {id: 8, courseName: 'C++'},
  {id: 9, courseName: 'Tenserflow'},
  {id: 10, courseName: 'Dialog Flow'},
  {id: 11, courseName: 'Flutter'},
  {id: 12, courseName: 'React Native'},
  {id: 13, courseName: 'Redux'},
  {id: 14, courseName: 'MongoDB'},
  {id: 15, courseName: 'PHP'},
  {id: 16, courseName: 'nodeJS'},
  {id: 17, courseName: 'Git'},
  {id: 19, courseName: 'Java'},
  {id: 20, courseName: 'HTML'},
  {id: 21, courseName: 'SCSS'},
  {id: 22, courseName: 'HTML5'},
  {id: 23, courseName: 'AI/ML'},
];
